# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eee32d98f650bf56530828de82c24f65321be076a6b9e3e8d73bb7f2e7bf0176b5a013c3f81a87842ea2b896731babb6eea916cab186dbf9f9d3605238f2d381

test:
  secret_key_base: 45765dd16070ad8ad7c5d32c6fc84c3b557d2237d5030ae578676c4a9c13a2b8a239ab8924945dcc00229e43a29c019fb54f7e51db66ab5a9c459de4a1a3a990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
